# Generated by Django 2.2.4 on 2019-10-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestpagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='static/imagenes'),
        ),
    ]
