# Generated by Django 2.2.4 on 2019-10-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestpagina', '0005_auto_20191025_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='reseña',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='reseña',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
